# -*- coding: utf-8 -*-
import time
from datetime import datetime

"""search4letters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZW5qdWKE2T_bn37rylzawh2soNhdZUb1
"""

def search4letters(word,letters='aeiou'):
  """ Funcion que busca las letras en una palabra y las imprime"""
  return set(word).intersection(letters)

help(search4letters)
search4letters('Hola me llamo ale')


def log_request(req: 'flask_request', res: str) -> None:
  with open('vsearch.log', 'a') as log:
    print(req.form,req.remote_addr,req.user_agent,
          str(datetime.today()),
          res, file=log,sep= '|')
